### ISSUE TITLE
Cannot give a post a title once created

### ISSUE THREAD

**Issue by kidGodzilla** [alexluong/scribbble-releases#1]
https://untitled.scribbble.co/posts/untitled-9z471g

**Comment by alexluong** [comment]
Hey, thanks for the bug report! I've fixed it and [a new version](https://github.com/alexluong/scribbble-releases/releases/tag/v0.1.6) is released.

It should auto update if you restart the app a few times 😅 (and wait for it to download the updates in the background)

I'm also adding a "Check for Updates..." menu action so this process is a little more streamlined.

The new release should be v0.1.6. You can check that at the top left menu item "Scribbble > About Scribbble".

Let me know if you're able to update to the latest version and if the bug is fixed!
